version: "3"

services:
  web:
    env_file: .env
  r5_api:
    container_name: r5_api
    restart: always
    build: .
    ports:
      - "3200:3000"
    links:
      - mongodb
    volumes:
      - ".:/app"
  mongodb:
    container_name: mongodb
    image: mongo
    logging: 
      driver: none
    ports: 
      - "27017:27017"
    volumes:
      - "./mongodb/:/data/db"
  volumes:
      - ./webapp:/opt/webapp
